### PR TITLE
Remove the OgRouteContext provider. This is now built in to OG.

### PR DESCRIPTION
**Pull request by pfrenssen**
A proposal is made to include a generic context provider in OG: https://github.com/Gizra/og/pull/180/

The context provider in OG Menu is now obsolete and might even conflict with the one from OG.

### CODE REVIEW

**Review by claudiu-cristea — CHANGES_REQUESTED** [review]
This seems a straight solution. I think the service should also be removed in `og_menu.services.yml`:

``` yaml
  og_menu.og_route_context:
    class: Drupal\og_menu\ContextProvider\OgRouteContext
    arguments: ['@current_route_match']
    tags:
      - { name: 'context_provider' }
```

BTW, before reviewing this I did a check also on https://github.com/Gizra/og/pull/180. Very nice work, congratulations!

**Review by claudiu-cristea — CHANGES_REQUESTED** [review]
See the above comment.

**Comment by claudiu-cristea** [comment]
I requested changes but the issue doesn't turn red. Seems that I don't have some permissions on this project?

**Review by claudiu-cristea — APPROVED** [review]
Approved

**Comment by pfrenssen** [comment]
Thanks for the review! Very good point, I also removed the declaration of the route context in the yaml file.

I don't know how the new review system works on Github, it opens some kind of floating dialog which I dislike.

**Comment by pfrenssen** [comment]
In the meantime I got the hang of the new review system, and @claudiu-cristea has the right permissions!

**Pull request merged**
